drop table if exists Member CASCADE;
create table Member
(
    id bigint generated by default as identity,
    name varchar(255),
    userId varchar(255),
    passwd varchar(255),
    primary key (id)
);

drop table if exists MemberToStudy CASCADE;
create table MemberToStudy
(
    id bigint generated by default as identity,
    memberId bigint,
    studyId bigint,
    foreign key (memberId) references Member(id) ON DELETE CASCADE,
    foreign key (studyId) references Study(id) ON DELETE CASCADE,
    primary key (id)
);

drop table if exists Study CASCADE;
create table Study
(
    id bigint generated by default as identity,
    name varchar(255),
    curUserCount int,
    maxUserCount int,
    goal varchar(255),
    details varchar(4095),
    leaderId bigint,
    foreign key (leaderId) references Member(id) ON DELETE CASCADE,
    primary key (id)
);

